-- MySQL Script generated by MySQL Workbench
-- Sun Mar 26 01:30:03 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `auta` DEFAULT CHARACTER SET utf8 ;
USE `auta` ;

-- -----------------------------------------------------
-- Table `mydb`.`auta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auta` (
  `idauta` INT NOT NULL AUTO_INCREMENT,
  `znacka` VARCHAR(50) NOT NULL,
  `model` VARCHAR(50) NOT NULL,
  `rok_vyroby` INT NOT NULL,
  PRIMARY KEY (`idauta`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
